application: gaewiki-demo
version: 1
runtime: python
api_version: 1

handlers:
- url: /gae-wiki-static/
  static_dir: gaewiki/static
- url: .*
  script: gaewiki

#- url: /static/
#  static_dir: static
#- url: /favicon.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico
#- url: .*
#  script: handlers.py

builtins:
- datastore_admin: on
